environments:
  # The "default" environment is available and used when `helmfile` is run without `--environment NAME`.
  #
  # these values are available to any values.yaml.gotmpl files but they are not passed into 
  # the helm charts directly
  default:
    values:
    - jx-values.yaml
    - versionStream/src/fake-secrets.yaml.gotmpl
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  values:
  - charts/jenkins-x/jxboot-helmfile-resources/values.yaml
- chart: jx3/jenkins-x-crds
- chart: stable/nginx-ingress
- chart: jenkins-x/tekton
- chart: jenkins-x/lighthouse
- chart: jenkins-x/bucketrepo
- chart: stable/docker-registry
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts

