name: BDD test
on:
#  push:
#    branches:
#    - main
#    - master

  # TODO disable kind BDD for now until it works reliably
  # pull_request:

  # allow manual triggering
  workflow_dispatch: {}
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Kind
      env:
        GIT_OWNER: jenkins-x-bdd
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        GITHUB_RUN_ID: ${{ secrets.GITHUB_RUN_ID }}
        GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
      run: |
        sudo -E .github/workflows/bdd.sh
